export const USER_TYPES = {
  USERS_START: "USERS_START",

  USERS_GET_ALL_SUCCESS: "USERS_GET_ALL_SUCCESS",
  USERS_GET_BY_ID_SUCCESS: "USERS_GET_BY_ID_SUCCESS",

  USER_DELETE_SUCCESS: "USER_DELETE_SUCCESS",
  USER_UPDATE_SUCCESS: "USER_UPDATE_SUCCESS",

  USERS_FAILURE: "USERS_FAILURE",
  USERS_CLEAR: "USERS_CLEAR",
};
